Repository AY2021S2-CS2103T-T12-1/tp, pull requests merged in 2021-04, with the labels that each got.

#106 Shift and Change Initialise Samples Method
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/garment/Colour.java
  src/main/java/seedu/address/model/garment/Garment.java
  src/main/java/seedu/address/ui/GarmentCard.java
  src/main/resources/images/beigeSample.jpg
  src/main/resources/images/beigeSamples/footwear.png
  src/main/resources/images/beigeSamples/lower.png
  src/main/resources/images/beigeSamples/upper.png
  src/main/resources/images/blackSample.jpg
  src/main/resources/images/blackSamples/footwear.png
  src/main/resources/images/blackSamples/lower.png
  src/main/resources/images/blackSamples/upper.png
  src/main/resources/images/blueSample.jpg
  src/main/resources/images/blueSamples/footwear.png
  src/main/resources/images/blueSamples/lower.png
  src/main/resources/images/blueSamples/upper.png
  src/main/resources/images/brownSample.jpg
  src/main/resources/images/brownSamples/footwear.png
  src/main/resources/images/brownSamples/lower.png
  src/main/resources/images/brownSamples/upper.png
  src/main/resources/images/footwear.jpeg
  src/main/resources/images/greenSample.jpg
  src/main/resources/images/greenSamples/footwear.png
  src/main/resources/images/greenSamples/lower.png
  src/main/resources/images/greenSamples/upper.png
  src/main/resources/images/greySample.jpg
  src/main/resources/images/greySamples/footwear.png
  src/main/resources/images/greySamples/lower.png
  src/main/resources/images/greySamples/upper.png
  src/main/resources/images/lower.jpeg
  src/main/resources/images/orangeSample.jpg
  src/main/resources/images/orangeSamples/footwear.png
  src/main/resources/images/orangeSamples/lower.png
  src/main/resources/images/orangeSamples/upper.png
  src/main/resources/images/pinkSample.jpg
  src/main/resources/images/pinkSamples/footwear.png
  src/main/resources/images/pinkSamples/lower.png
  src/main/resources/images/pinkSamples/upper.png
  src/main/resources/images/purpleSample.jpg
  src/main/resources/images/purpleSamples/footwear.png
  src/main/resources/images/purpleSamples/lower.png
  src/main/resources/images/purpleSamples/upper.png
  src/main/resources/images/redSample.jpg
  src/main/resources/images/redSamples/footwear.png
  src/main/resources/images/redSamples/lower.png
  src/main/resources/images/redSamples/upper.png
  src/main/resources/images/upper.jpeg
  src/main/resources/images/whiteSample.jpg
  src/main/resources/images/whiteSamples/footwear.png
  src/main/resources/images/whiteSamples/lower.png
  src/main/resources/images/whiteSamples/upper.png
  src/main/resources/images/yellowSample.jpg
  src/main/resources/images/yellowSamples/footwear.png
  src/main/resources/images/yellowSamples/lower.png
  src/main/resources/images/yellowSamples/upper.png
Labels: enhancement

#108 Update UG 1.3
  docs/UserGuide.md
Labels: documentation

#149 Add sorting
  src/main/java/seedu/address/model/Wardrobe.java
  src/main/java/seedu/address/model/garment/Garment.java
  src/main/java/seedu/address/model/garment/GarmentComparator.java
  src/main/java/seedu/address/model/garment/UniqueGarmentList.java
Labels: enhancement

#151 Edit LastUsed to support Never
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/model/garment/Garment.java
  src/main/java/seedu/address/model/garment/GarmentComparator.java
  src/main/java/seedu/address/model/garment/LastUse.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: enhancement

#154 Update UG to fix bugs found
  docs/UserGuide.md
  docs/images/AddGarment.png
  docs/images/ClearGarment.png
  docs/images/DeleteGarment.png
  docs/images/EditGarment.png
  docs/images/FindGarmentA.png
  docs/images/FindGarmentB.png
  docs/images/ListGarment.png
  docs/images/MatchGarment.png
  docs/images/SelectGarment.png
  docs/images/Ui.png
  docs/images/ViewGarment.png
  src/main/java/seedu/address/model/garment/Colour.java
Labels: bug

#155 Fix PE-D Issues
  docs/UserGuide.md
  src/main/java/seedu/address/model/garment/Colour.java
  src/main/java/seedu/address/model/garment/Garment.java
  src/main/java/seedu/address/model/garment/Size.java
  src/main/java/seedu/address/ui/GarmentCard.java
  src/main/resources/view/GarmentListCard.fxml
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/garment/SizeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedGarmentTest.java
Labels: bug, documentation

#156 Visnu PPP 1.4
  docs/team/Visnu_PPP.md
  docs/team/johndoe.md
Labels: documentation

#158 Added the PPP for arihantjain97
  docs/team/arihantjain97.md
Labels: documentation

#159 PPP Draft by Jonathan
  docs/team/jonathan-cao.md
Labels: documentation

#160 Aditya's project portfolio page
  docs/team/adidoesnt.md
Labels: documentation

#161 visnuravi PPP-1.4
  docs/team/visnuravi.md
Labels: documentation

#162 Update adidoesnt.md
  docs/team/adidoesnt.md
Labels: documentation

#163 Issues fixed: 138,114,111,110
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: bug, documentation

#164 Added new restrictions for List Command (no arguments taken)
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/WardrobeParser.java
  src/test/java/seedu/address/logic/parser/WardrobeParserTest.java
Labels: bug, enhancement

#165 Fix More PED Issues
  docs/UserGuide.md
Labels: documentation

#166 Desc Bug 1.4
  src/main/java/seedu/address/model/description/Description.java
  src/main/java/seedu/address/ui/GarmentCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/GarmentListCard.fxml
Labels: bug, enhancement

#168 Add DG diagrams
  docs/DeveloperGuide.md
Labels: documentation

#169 Fix Find Command Parser to reject redundant search query parameters
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: enhancement

#170 Fix bugs pertaining to view and dress code
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/garment/DressCode.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: enhancement

#172 DG: Finish Select Command with UML diagrams and elaboration
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/SelectActivityDiagram.puml
  docs/diagrams/SelectSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/SelectActivityDiagram.png
  docs/images/SelectSequenceDiagram.png
  src/main/java/seedu/address/ui/GarmentCard.java
  src/main/resources/view/GarmentListCard.fxml
Labels: documentation

#173 Add Match sequence and activity diagrams, and edit developer guide
  docs/DeveloperGuide.md
  docs/diagrams/MatchActivityDiagram.puml
  docs/diagrams/MatchSequenceDiagram.puml
Labels: documentation

#176 Add activity and sequence diagrams to developer guide
  docs/DeveloperGuide.md
  docs/diagrams/MatchActivityDiagram.puml
  docs/images/MatchActivityDiagram.png
  docs/images/MatchSequenceDiagram.png
Labels: documentation

#177 Added DG details: Add Use Case
  docs/DeveloperGuide.md
  docs/SettingUp.md
Labels: documentation

#178 Add use case for match
  docs/DeveloperGuide.md
Labels: documentation

#179 Update NuFash Website
  README.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/SelectSequenceDiagram.png
  docs/images/Ui.png
  docs/images/ViewSequenceDiagram.png
  docs/index.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: documentation

#180 Update DG 1.4
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/MatchSequenceDiagram.puml
  docs/diagrams/SelectSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/MatchSequenceDiagram.png
  docs/images/SelectSequenceDiagram.png
Labels: documentation

#181 Added Shortcuts: CRUD and Command Cycling
  src/main/java/seedu/address/ui/CommandBox.java
Labels: enhancement

#182 Update DG with View Use Case
  docs/DeveloperGuide.md
Labels: documentation

#183 Add Find Use Case
  docs/DeveloperGuide.md
  docs/SettingUp.md
Labels: documentation

#184 Update DG table
  docs/DeveloperGuide.md
  docs/_sass/minima/_base.scss
Labels: documentation

#185 Update User Stories in DG
  docs/DeveloperGuide.md
  docs/team/jonathan-cao.md
Labels: documentation

#186 Edit project portfolio page for adidoesnt
  docs/team/adidoesnt.md
Labels: documentation

#187 Add commas between PR links
  docs/team/adidoesnt.md
Labels: documentation

#188 Fix User Stories Table in DG for HTML
  docs/DeveloperGuide.md
Labels: documentation

#189 Desc and Name bug 1.4
  docs/UserGuide.md
  src/main/java/seedu/address/model/description/Description.java
  src/main/java/seedu/address/model/garment/Name.java
  src/main/java/seedu/address/model/garment/Size.java
  src/main/java/seedu/address/ui/GarmentCard.java
  src/main/resources/view/GarmentListCard.fxml
  src/test/java/seedu/address/model/garment/NameContainsKeywordsPredicateTest.java
Labels: bug

#190 Visnu PPP 1.4
  docs/team/visnuravi.md
Labels: documentation

#192 Edit PPP
  docs/team/visnuravi.md
Labels: documentation

#193 Edit PPP
  docs/team/visnuravi.md
Labels: documentation

#194 Edit PPP
  docs/team/visnuravi.md
Labels: documentation

#195 Update table of contents and screenshots for user guide
  docs/UserGuide.md
  docs/images/AddGarment.png
  docs/images/ClearGarment.png
  docs/images/DeleteGarment.png
  docs/images/EditGarment.png
  docs/images/FindGarmentA.png
  docs/images/FindGarmentB.png
  docs/images/ListGarment.png
  docs/images/MatchGarment.png
  docs/images/SelectGarment.png
  docs/images/ViewGarment.png
Labels: documentation

#196 Add Feedback Box and Wardrobe Box Diagrams
  docs/images/feedback-box.png
  docs/images/wardrobe-box.png
Labels: documentation

#197 Arihant PPP edits
  docs/UserGuide.md
  docs/team/arihantjain97.md
Labels: documentation

#198 Update ViewGarment image
  docs/DeveloperGuide.md
  docs/images/ViewGarment.png
Labels: documentation

#199 Update UG 1.4
  docs/UserGuide.md
Labels: documentation

#200 Update UG and DG headers
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#202 Fix invalid input for Find
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: bug

#203 Update UG page breaks
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation

#204 Add more page breaks to UG
  docs/UserGuide.md
Labels: documentation

#205 More page breaks to UG
  docs/UserGuide.md
Labels: documentation
